name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: fetch bazelisk
      run: |
        wget -O bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.2.1/bazelisk-linux-amd64
        chmod +x ./bazelisk
    - name: test
      run: ./bazelisk test //test
